### ISSUE TITLE
The tools are not displayed in hand like other tools

### ISSUE THREAD

**Issue by maximc6** [jaymanh/OP-Tools-Fabric-Old#1]
![optools](https://github.com/user-attachments/assets/523c223b-463f-4d46-981d-a7b5703e57f7)
![regulartools](https://github.com/user-attachments/assets/b3737f84-c3dd-41c5-b0b0-9d0d62decc2a)

**Comment by jaymanh** [comment]
Thanks for letting me know!

Its all fixed now in the newest version.
